import "@/styles/globals.css";

import type { Metadata } from "next";
import { AppBar, NavigationRail } from "../components/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppBar />
        <div id="root" className="flex items-center justify-center">
          <NavigationRail />
          <div className="m-[80px]">
            {children}
          </div>
          </div>
      </body>
    </html>
  );
}
