import "@/styles/globals.css";

import type { Metadata } from "next";
import { AppBar, BodyWrapper, NavigationRail } from "../components/Shell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="root" className="h-[100dvh] flex align-top items-start overflow-hidden relative overscroll-none">
          <BodyWrapper>
            {children}
          </BodyWrapper>
          <NavigationRail />
          <AppBar />
          </div>
      </body>
    </html>
  );
}
